language: node_js
node_js:
 - "node"

cache: npm

script:
- echo "VUE_APP_FirebaseAPIKey=$FirebaseAPIKey" > .env.local
- npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist
 on:
   branch: master
